# ただのメモ

## 1. <class 'sklearn.utils.Bunch'>のデータ
### 1.1 概要
sklearn.utils.Bunchは、Pythonの辞書(dict)と非常に似た形式でデータを格納するための独自のクラスです。Bunchオブジェクトは、キーと値のペアを持つ属性としてアクセスできます。
### 1.2 キーを見てみる

In [2]:
# Bunchオブジェクトをロードする
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


### 1.3 それぞれのキー

* 'data': サンプルの特徴量を格納した2次元配列
* 'target': 各サンプルに対するクラスのラベルを格納した1次元配列
* 'frame': PandasのDataFrameとして格納された場合、そのDataFrameを返します
* 'target_names': クラスの名前を格納した1次元配列
* 'DESCR': データセットの説明を格納した文字列
* 'feature_names': 各特徴量の名前を格納した1次元配列
* 'filename': データセットのファイル名を格納した文字列

In [5]:
'''
'data': サンプルの特徴量を格納した2次元配列
'target': 各サンプルに対するクラスのラベルを格納した1次元配列
'frame': PandasのDataFrameとして格納された場合、そのDataFrameを返します
'target_names': クラスの名前を格納した1次元配列
'DESCR': データセットの説明を格納した文字列
'feature_names': 各特徴量の名前を格納した1次元配列
'filename': データセットのファイル名を格納した文字列'''
print("iris[data] = ", iris['data'])
print("iris[target] = ", iris['target'])
print("iris[frame] = ", iris['frame'])
print("iris[target_names] = ", iris['target_names'])
print("iris[DESCR] = ", iris['DESCR'])
print("iris[feature_names] = ", iris['feature_names'])
print("iris[filename] = ", iris['filename'])



iris[data] =  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5

## 2. マジックメソッド

\_\_〇〇\_\_ の形をしたあれのこと。

### 2.1 マジックメソッドの一例
以下に一例を書きます。
- `__len__(self)`: オブジェクトの長さを返すために使用されるメソッド。たとえば、`len(obj)`と書くと、`obj.__len__()`が呼び出されます。
- `__getitem__(self, key)`: オブジェクトから要素を取得するために使用されるメソッド。たとえば、`obj[key]`と書くと、`obj.__getitem__(key)`が呼び出されます。
- `__setitem__(self, key, value)`: オブジェクトに要素を設定するために使用されるメソッド。たとえば、`obj[key] = value`と書くと、`obj.__setitem__(key, value)`が呼び出されます。
- `__delitem__(self, key)`: オブジェクトから要素を削除するために使用されるメソッド。たとえば、`del obj[key]`と書くと、`obj.__delitem__(key)`が呼び出されます。
- `__str__(self)`: オブジェクトの文字列表現を返すために使用されるメソッド。たとえば、`print(obj)`と書くと、`obj.__str__()`が呼び出されます。
- `__repr__(self)`: オブジェクトの正確な文字列表現を返すために使用されるメソッド。たとえば、`obj`と書くと、`obj.__repr__()`が呼び出されます。

他にも、演算子(+)に関するものだったり。比較演算子(<)とかに関するものだったり色々ある。


### 2.2 マジックメソッドの実装

In [42]:
# 動作確認
class MyList:
    def __init__(self, lst):
        print("init")
        self.lst = lst

    def __len__(self):
        print("len")
        return len(self.lst)

    def __getitem__(self, idx):
        print("getitem")
        return self.lst[idx]

    def __setitem__(self, idx, value):
        print("setitem")
        self.lst[idx] = value

    def __delitem__(self, idx):
        print("delitem")
        del self.lst[idx]

    def __str__(self):
        print("str")
        return str(self.lst)
    def __repr__(self):
        print("repr")
        return repr(self.lst)

my_list = MyList([1, 2, 3, 4, 5])

print(len(my_list))  # 5

print(my_list[2])  # 3

my_list[2] = 6
print(my_list[2])  # 6

print(my_list)  # [1, 2, 6, 4, 5]

del my_list[3]

print(my_list)  # [1, 2, 6, 5]
my_list# [1, 2, 6, 5]


init
len
5
getitem
3
setitem
getitem
6
str
[1, 2, 6, 4, 5]
delitem
str
[1, 2, 6, 5]
repr


[1, 2, 6, 5]

## 3 <class 'PIL.Image.Image'>のデータ

## 4. <class 'torchvision.datasets.mnist.MNIST'>

あなたはプロのプログラマーです。

私は素人プログラマーであり、私はあなたにプログラミングの質問をします。私の質問に対し、あなたは素人プログラマーがわかるように回答をしてください。ただし、私は素人プログラマーのため、質問しようにも周辺知識が足りず、質問が不完全なことがかなりの確率であります。なので、あなたは質問の内容不足で最高の回答がつくれそうにない場合、積極的に私に質問を補完するための情報提供を投げかけてください。

## 5.for文について

用語の整理

* イテラブル(オブジェクト)とは\_\_iter\_\_メソッドを実装しているオブジェクトを指します。
* イテレータ(オブジェクト)とは、\_\_iter\_\_と\_\_next\_\_メソッドが実装されておりさらに\_\_iter\_\_の返り値が自分自身、つまりiter(obj)=objの物をいう。
* \_\_iter\_\_と\_\_next\_\_メソッドが実装されているが\_\_iter\_\_の返り値が自分自身でないものには特に名前をつけられていない(聞いたことがないだけかも)

for i in obj: は以下のプロセスで動作している。
1. iter(obj)を実行する。この結果は今後も使うので便宜上、obj_iとしておく。
2. iにnext(obj_i)を代入する。このとき、StopIteration(エラーの一種？)が起きた場合、4番に処理をする。
3. for内部の処理を実行し、breakがなければ2番に戻る。あったら4番に行く。
4. for文終了


In [123]:
# イテラブルなクラス
class MyList_iterable:
    def __init__(self, data):
        self.data = data
        self.index = 0
    
    def __iter__(self,iterator=False):
        # nextだけを実装したクラスを返す。つまりイテレータではない。
        return MyList_next_implementation(self.data)

# ネクストだけ実装されたクラス(ネクストがあるのにイテレータではない)
class MyList_next_implementation:
    def __init__(self, data):
        self.data = data
        self.index = 0
    
    def __next__(self):
        if self.index == len(self.data):
            raise StopIteration
        value = self.data[self.index]
        self.index += 1
        return value * 2

# イテレータなクラス
class MyList_iterator:
    def __init__(self, data):
        self.data = data
        self.index = 0
    
    def __iter__(self):
        return self
    
    def __next__(self):
        if self.index == len(self.data):
            raise StopIteration
        value = self.data[self.index]
        self.index += 1
        return value * 2
    
my_list = MyList_iterable([1, 2, 3, 4, 5])
my_list_iter = MyList_iterator([1, 2, 3, 4, 5])
my_list_no_iter = iter(my_list)

for i in my_list: # iter(my_list)の結果はイテレータではないがnextがあるので、for文を回せる。
    print(i)

for i in my_list_iter: # iter(my_list)の結果自分自身で自分自身はnextをもつので、for文を回せる。
    print(i)

try:
    for i in my_list_no_iter: # iterがないのでエラー
        print(i)
except TypeError as e:
    print(e)

2
4
6
8
10
2
4
6
8
10
'MyList_next_implementation' object is not iterable


## 6. <class 'torch.utils.data.dataloader.DataLoader'>のデータ
### 6.1　<class 'torch.utils.data.dataloader.DataLoader'>のデータがどのようなメソッドや属性を持つか説明

### メソッド

- `__init__(self, dataset, batch_size=1, shuffle=False, sampler=None, batch_sampler=None, num_workers=0, collate_fn=None, pin_memory=False, drop_last=False, timeout=0, worker_init_fn=None, multiprocessing_context=None)` : DataLoader オブジェクトを初期化します。
- `__iter__(self)` : DataLoader からイテレータを取得します。
- `__len__(self)` : DataLoader が読み込むデータセットのバッチ数を返します。
- `__next__(self)` : イテレータから次のバッチを取得します。
- `__len__(self)` : DataLoader が読み込むデータセットのバッチ数を返します。

### 属性

- `dataset` : DataLoader が読み込む元となるデータセットを表します。
- `batch_size` : DataLoader が返すバッチのサイズを表します。
- `collate_fn` : バッチに含まれる各サンプルの処理方法を定義する関数を表します。
- `num_workers` : バッチの読み込みを行うプロセスの数を表します。
- `sampler` : データセットのサンプルの取得方法を定義するオブジェクトを表します。
- `shuffle` : データセットのサンプルをシャッフルするかどうかを表します。
- `drop_last` : 最後のバッチのサンプル数がバッチサイズより小さい場合に、それを無視するかどうかを表します。

## 7. 逆誤差伝播法

大体わかったので書いておく。





## 8. デコレータの話
https://qiita.com/_rdtr/items/d3bc1a8d4b7eb375c368
わかりやすかった。

関数は引数を辞書としてローカルスコープに保持する、変数の解決規則と関数定義の際にそれがグローバルスコープでないなら自分を囲むスコープの情報を保持するのが肝。

*args と **kwargsのパックとアンパックの話も面白い。